# Generated by Django 3.0.8 on 2020-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.URLField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
